apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::133600292679:role/eksctl-eksctl-demo-nodegroup-ng-09-NodeInstanceRole-sQUVegMH3h9p
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::133600292679:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-27T07:05:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1470"
  uid: 2dc3fd0e-57fb-4b9d-9918-bee676b5d730
